name: Windower & Ashita Addon Release

on:
  push:
    branches:
      - main
    paths:
      - 'Ashita/**'
      - 'Windower4/**'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get version from commit message
      id: get_version
      run: |
        # Extract version like v1.2.3 or 1.2.3 from commit message
        VERSION=$(echo "${{ github.event.head_commit.message }}" | grep -oE 'v?[0-9]+\.[0-9]+\.[0-9]+')
        VERSION=${VERSION#v}  # remove leading 'v' if present
        if [ -z "$VERSION" ]; then
          echo "No version found in commit message. Using default 0.0.0"
          VERSION="0.0.0"
        fi
        echo "version=$VERSION" >> $GITHUB_ENV
        echo "Using version $VERSION"

    - name: Build Ashita Addon ZIP
      if: contains(join(github.event.commits.*.modified, ' '), 'Ashita/') || contains(join(github.event.commits.*.added, ' '), 'Ashita/')
      run: |
        mkdir -p ashita-addon/addons/whereisnm
        cp Ashita/*.lua ashita-addon/addons/whereisnm/
        cd ashita-addon
        zip -r ../ashita-addon-$VERSION.zip addons/
        cd ..

    - name: Build Windower Addon ZIP
      if: contains(join(github.event.commits.*.modified, ' '), 'Windower4/') || contains(join(github.event.commits.*.added, ' '), 'Windower4/')
      run: |
        mkdir -p windower-addon/addons/whereisnm
        cp Windower4/*.lua windower-addon/addons/whereisnm/
        cd windower-addon
        zip -r ../windower-addon-$VERSION.zip addons/
        cd ..

    - name: Create GitHub Release for Ashita
      if: exists('ashita-addon-' + env.version + '.zip')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "ashita-v${{ env.version }}"
        name: "Ashita Addon Release v${{ env.version }}"
        body: "Ashita addon release v${{ env.version }}"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Ashita ZIP
      if: exists('ashita-addon-' + env.version + '.zip')
      uses: softprops/action-gh-release@v1
      with:
        files: "ashita-addon-$VERSION.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release for Windower
      if: exists('windower-addon-' + env.version + '.zip')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "windower-v${{ env.version }}"
        name: "Windower Addon Release v${{ env.version }}"
        body: "Windower addon release v${{ env.version }}"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Windower ZIP
      if: exists('windower-addon-' + env.version + '.zip')
      uses: softprops/action-gh-release@v1
      with:
        files: "windower-addon-$VERSION.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
