name: Windower & Ashita Addon Release

on:
  push:
    branches:
      - main
    paths:
      - 'Ashita/**'
      - 'Windower4/**'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get version from commit message
      id: get_version
      run: |
        VERSION=$(echo "${{ github.event.head_commit.message }}" | grep -oE 'v?[0-9]+\.[0-9]+\.[0-9]+')
        VERSION=${VERSION#v}  # remove leading 'v' if present
        if [ -z "$VERSION" ]; then
          echo "No version found in commit message. Using default 0.0.0"
          VERSION="0.0.0"
        fi
        echo "version=$VERSION" >> $GITHUB_ENV
        echo "Using version $VERSION"

    - name: Configure git for tagging
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Create Git tag
      run: |
        git tag -f "v${{ env.version }}" -m "Release v${{ env.version }}"
        git push origin --tags --force

    # --- Ashita ---
    - name: Check if Ashita folder changed
      id: ashita_changed
      run: |
        if git diff --name-only HEAD~1 HEAD | grep -q '^Ashita/'; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT

    - name: Build Ashita Addon ZIP
      if: steps.ashita_changed.outputs.changed == 'true'
      id: build_ashita
      run: |
        mkdir -p ashita-addon/addons/whereisnm
        cp Ashita/*.lua ashita-addon/addons/whereisnm/
        cd ashita-addon
        zip -r ../ashita-addon-${{ env.version }}.zip addons/
        cd ..
        echo "zip_exists=true" >> $GITHUB_OUTPUT

    - name: Create GitHub Release for Ashita
      if: steps.build_ashita.outputs.zip_exists == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v${{ env.version }}"
        name: "Ashita Addon Release v${{ env.version }}"
        body: "Ashita addon release v${{ env.version }}"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Ashita ZIP
      if: steps.build_ashita.outputs.zip_exists == 'true'
      uses: softprops/action-gh-release@v1
      with:
        files: "ashita-addon-${{ env.version }}.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # --- Windower ---
    - name: Check if Windower4 folder changed
      id: windower_changed
      run: |
        if git diff --name-only HEAD~1 HEAD | grep -q '^Windower4/'; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT

    - name: Build Windower Addon ZIP
      if: steps.windower_changed.outputs.changed == 'true'
      id: build_windower
      run: |
        mkdir -p windower-addon/addons/whereisnm
        cp Windower4/*.lua windower-addon/addons/whereisnm/
        cd windower-addon
        zip -r ../windower-addon-${{ env.version }}.zip addons/
        cd ..
        echo "zip_exists=true" >> $GITHUB_OUTPUT

    - name: Create GitHub Release for Windower
      if: steps.build_windower.outputs.zip_exists == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v${{ env.version }}"
        name: "Windower Addon Release v${{ env.version }}"
        body: "Windower addon release v${{ env.version }}"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Windower ZIP
      if: steps.build_windower.outputs.zip_exists == 'true'
      uses: softprops/action-gh-release@v1
      with:
        files: "windower-addon-${{ env.version }}.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
