name: Release Addon

on:
  push:
    branches: [ main ]
    paths:
      - 'Windower4/**'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Extract version from commit message
      id: version
      run: |
        VERSION=$(echo "${{ github.event.head_commit.message }}" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
        
        if [ -z "$VERSION" ]; then
          echo "No version found in commit message: ${{ github.event.head_commit.message }}"
          exit 1
        fi
        
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Found version: $VERSION"

    - name: Create addon directory structure
      run: |
        mkdir -p addons/whereisnm
        
        cp Windower4/whereisnm.lua addons/whereisnm/
        cp Windower4/api.lua addons/whereisnm/
        cp Windower4/sha2.lua addons/whereisnm/

    - name: Create zip file
      run: |
        zip -r whereisnm-v${{ steps.version.outputs.version }}.zip addons/

    - name: Create or update release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        TAG="v$VERSION"
        ZIP_FILE="whereisnm-v$VERSION.zip"
        
        if gh release view "$TAG" >/dev/null 2>&1; then
          echo "Release $TAG exists, uploading asset..."
          gh release delete-asset "$TAG" "$ZIP_FILE" --yes || true
          gh release upload "$TAG" "$ZIP_FILE"
        else
          echo "Creating new release $TAG..."
          RELEASE_NOTES="Release v$VERSION

        Changes:
        ${{ github.event.head_commit.message }}"
          
          gh release create "$TAG" "$ZIP_FILE" --title "WhereIsNM v$VERSION" --notes "$RELEASE_NOTES"
        fi